services:
  db:
    image: postgres:17
    container_name: finance-postgres

    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finance_user -d finance"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: